### ISSUE TITLE
Revision of Guides on Assessment Guide

### ISSUE THREAD

**Issue by chachtel1** [Allegheny-Computer-Science-203-S2020/cs203-S2020-assessment#16]
At this moment, the "Revision of Guides" section on the assessment.md file shows that we as students should write self-assessment paragraphs, with the 😎 only being given to someone who has edited the assessment and code of conduct documents.  This is not something that we should be required to do for a grade.  It should instead only be used as an administrative guide.

**Comment by guzmanr04** [comment]
Yeah, that sounds like it would be an issue that should be addressed.

**Comment by koscinskic** [comment]
There are a variety of tasks covered in the assessment guide (including this task) that seem poorly suited to be addressed by every individual student. We could have a meeting outside of class to discuss what we as contributors feel should be modified in the assessment guide in general and propose said changes to Professor Kapfhammer, along with this current issue.

**Comment by gkapfham** [comment]
What if the status of this issue? Thanks for any updates!!
