### ISSUE TITLE
Team3-assessment-individual-thoughts

### ISSUE THREAD

**Issue by liux2** [Allegheny-Computer-Science-203-S2020/cs203-S2020-assessment#8]
Markdown:
Tab from line 77 to line 91?

Commit: https://github.com/Allegheny-Computer-Science-203-S2020/cs203-S2020-assessment/commit/b5e63e8d381f69861a555b07e0a00df904aa57f0

**Comment by liux2** [comment]
Like in commit https://github.com/Allegheny-Computer-Science-203-S2020/cs203-S2020-assessment/commit/46d75350fb8f8d2a26cb9f42417252acdb5cac0d

**Comment by Jordan-A** [comment]
Under the bullet point of Continuous Integration with Travis the abbreviation config is being used. Might be better using the full word configuration?

**Comment by hodevin** [comment]
@Jordan-A That would be more appropriate.

**Comment by lussierc** [comment]
I would agree @Jordan-A.

**Comment by lussierc** [comment]
As a pull request (PR #15) has now been made for the work discussed in this Issue, I am closing the Issue.

Any further discussion about this section should continue in the aforementioned PR.
