### ISSUE TITLE
Markdown-template-update-README

### ISSUE THREAD

**Issue by bagashvilit** [Allegheny-Computer-Science-203-S2020/cs203-S2020-assessment#9]
Since Markdown team suggested to use Emojis, but README.md file still uses letters as assessment Should we update README.md ?

**Comment by noorbuchi** [comment]
@bagashvilit thanks for raising this issue! We will update the README file to include emojis similar to the assessment file.

**Comment by Jordan-A** [comment]
I think it would be a great idea to update the readme.md FILE.

**Comment by noorbuchi** [comment]
@bagashvilit  which branch do you suggest I make the changes to?

**Comment by bagashvilit** [comment]
@noorbuchi I think it would be great if we could make changes to the master branch so that everyone can see it, what do you think?

**Comment by bagashvilit** [comment]
@noorbuchi if we try to make changes to the master, I guess we would need a pull request
